#
# Quart-Bcrypt documentation build configuration file, created by
# sphinx-quickstart on Sundaty October 10 11:00 2021.
# 
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#

# Project --------------------------------------------------------------

project = "Quart-Bcrypt"
copyright = "2020 Chris Rood"
author = "Chris Rood"
release, version = "0.0.4"

# General --------------------------------------------------------------

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinxcontrib.log_cabinet",
    "sphinx.ext.napoleon",
    "pydata-sphinx-theme",
    "sphinx_issues",
]
autodoc_typehints = "description"
intersphinx_mapping = {
    "python": ("https://docs.python.org/3.9/", None),
    "quart": ("https://pgjones.gitlab.io/quart/", None),
    "bcrypt": ("https://github.com/pyca/bcrypt/", None),
}
issues_github_path = "crood58/quart-bcrypt"

# HTML -----------------------------------------------------------------

html_theme = "pydata_sphinx_theme"

html_theme_options = {
  "external_links": [
      {"name": "PyPI Releases", "url": "https://github.com/crood58/quart-bcrypt/issues"},
      {"name": "Source code", "url": "https://github.com/crood58/quart-bcrypt"},
      {"name": "Issues", "url": "https://github.com/crood58/quart-bcrypt/issues"},
  ]
}